import type { Book, LoanWithBook } from "./types";

const raw: Array<
  Pick<Book, "id" | "title" | "author" | "category" | "description" | "isbn" | "published_year" | "total_copies">
> = [
  {
    id: "b1",
    title: "สถาปัตยกรรมซอฟต์แวร์ที่สะอาด",
    author: "Robert C. Martin",
    category: "เทคโนโลยี",
    description: "หลักการออกแบบระบบให้ยืดหยุ่น ทดสอบง่าย และอยู่ได้นานกว่าอายุของเฟรมเวิร์กที่ใช้",
    isbn: "9780134494166",
    published_year: 2017,
    total_copies: 3,
  },
  {
    id: "b2",
    title: "คิด เร็ว และ ช้า",
    author: "Daniel Kahneman",
    category: "จิตวิทยา",
    description: "ระบบคิดสองแบบในสมองมนุษย์ กับกับดักการตัดสินใจที่เราไม่รู้ตัว",
    isbn: "9780374533557",
    published_year: 2011,
    total_copies: 2,
  },
  {
    id: "b3",
    title: "Sapiens ประวัติย่อมนุษยชาติ",
    author: "Yuval Noah Harari",
    category: "ประวัติศาสตร์",
    description: "จากลิงไร้ขนสู่ผู้ครองโลก เรื่องเล่าที่เปลี่ยนมุมมองที่เรามีต่อตัวเอง",
    isbn: "9780062316097",
    published_year: 2014,
    total_copies: 4,
  },
  {
    id: "b4",
    title: "Atomic Habits",
    author: "James Clear",
    category: "พัฒนาตนเอง",
    description: "เปลี่ยนชีวิตด้วยนิสัยเล็ก ๆ ที่ทำได้ทุกวัน แทนการตั้งเป้าหมายที่ใหญ่เกินตัว",
    isbn: "9780735211292",
    published_year: 2018,
    total_copies: 5,
  },
  {
    id: "b5",
    title: "เจ้าชายน้อย",
    author: "Antoine de Saint-Exupéry",
    category: "วรรณกรรม",
    description: "นิทานสำหรับผู้ใหญ่ที่ยังไม่ลืมความเป็นเด็ก",
    isbn: "9780156012195",
    published_year: 1943,
    total_copies: 2,
  },
  {
    id: "b6",
    title: "The Pragmatic Programmer",
    author: "Andrew Hunt, David Thomas",
    category: "เทคโนโลยี",
    description: "คู่มือช่างฝีมือนักเขียนโปรแกรม ฉบับครบรอบ 20 ปี",
    isbn: "9780135957059",
    published_year: 2019,
    total_copies: 3,
  },
  {
    id: "b7",
    title: "ปัญญาประดิษฐ์ฉบับเข้าใจง่าย",
    author: "Melanie Mitchell",
    category: "เทคโนโลยี",
    description: "AI ทำอะไรได้จริง และอะไรคือเรื่องเล่าเกินจริงที่เราได้ยินกันทุกวัน",
    isbn: "9780374257835",
    published_year: 2019,
    total_copies: 2,
  },
  {
    id: "b8",
    title: "บ้านเล็กในป่าใหญ่",
    author: "Laura Ingalls Wilder",
    category: "วรรณกรรม",
    description: "ชีวิตครอบครัวผู้บุกเบิกกลางป่าอเมริกัน เล่าอย่างอบอุ่นและเรียบง่าย",
    isbn: "9780064400015",
    published_year: 1932,
    total_copies: 1,
  },
  {
    id: "b9",
    title: "เศรษฐศาสตร์เปลือย",
    author: "Charles Wheelan",
    category: "เศรษฐศาสตร์",
    description: "อธิบายเศรษฐศาสตร์แบบไม่ต้องมีสมการสักบรรทัด",
    isbn: "9780393337648",
    published_year: 2010,
    total_copies: 3,
  },
  {
    id: "b10",
    title: "Design of Everyday Things",
    author: "Don Norman",
    category: "ออกแบบ",
    description: "ทำไมประตูบางบานถึงผลักไม่ถูกด้าน — ว่าด้วยการออกแบบที่เข้าใจคน",
    isbn: "9780465050659",
    published_year: 2013,
    total_copies: 2,
  },
  {
    id: "b11",
    title: "จิตวิทยาว่าด้วยเงิน",
    author: "Morgan Housel",
    category: "การเงิน",
    description: "ความมั่งคั่งไม่ได้มาจากสูตรคำนวณ แต่มาจากพฤติกรรมที่ทำซ้ำได้",
    isbn: "9780857197689",
    published_year: 2020,
    total_copies: 4,
  },
  {
    id: "b12",
    title: "ดินแดนแห่งความเงียบ",
    author: "Erling Kagge",
    category: "ปรัชญา",
    description: "ความเงียบในยุคที่โลกส่งเสียงตลอดเวลา",
    isbn: "9781524704872",
    published_year: 2017,
    total_copies: 1,
  },
];

/** จำนวนเล่มที่ถูกยืมอยู่ในโหมดตัวอย่าง (ให้หน้าเว็บมีทั้งสถานะว่างและถูกยืมหมด) */
const borrowed: Record<string, number> = { b2: 2, b4: 1, b8: 1, b12: 1 };

export const demoBooks: Book[] = raw.map((b, i) => ({
  ...b,
  color: null,
  cover_url: null,
  created_at: new Date(Date.now() - i * 86_400_000).toISOString(),
  available_copies: b.total_copies - (borrowed[b.id] ?? 0),
}));

const day = 86_400_000;

export const demoLoans: LoanWithBook[] = [
  {
    id: "l1",
    book_id: "b4",
    member_id: "demo-user",
    borrowed_at: new Date(Date.now() - 3 * day).toISOString(),
    due_at: new Date(Date.now() + 11 * day).toISOString(),
    returned_at: null,
    status: "borrowed",
    created_at: new Date(Date.now() - 3 * day).toISOString(),
    book: demoBooks.find((b) => b.id === "b4")!,
  },
  {
    id: "l2",
    book_id: "b12",
    member_id: "demo-user",
    borrowed_at: new Date(Date.now() - 20 * day).toISOString(),
    due_at: new Date(Date.now() - 6 * day).toISOString(),
    returned_at: null,
    status: "borrowed",
    created_at: new Date(Date.now() - 20 * day).toISOString(),
    book: demoBooks.find((b) => b.id === "b12")!,
  },
  {
    id: "l3",
    book_id: "b5",
    member_id: "demo-user",
    borrowed_at: new Date(Date.now() - 40 * day).toISOString(),
    due_at: new Date(Date.now() - 26 * day).toISOString(),
    returned_at: new Date(Date.now() - 28 * day).toISOString(),
    status: "returned",
    created_at: new Date(Date.now() - 40 * day).toISOString(),
    book: demoBooks.find((b) => b.id === "b5")!,
  },
];
